#!/usr/bin/env bash
# ── Subconscious API Gateway — OpenCode setup ─────────────────────────────────
# Point OpenCode at your gateway. Writes a provider config with session headers
# so the gateway can correlate OpenCode requests into Conversations.
#
# Quick start:
#   ./install.sh install --gateway-url https://your-gateway.example --api-key sk-gw-...
#   ./install.sh status                 # show current config
#   ./install.sh uninstall              # revert to default opencode config
#
# Writes ~/.opencode/opencode.json (user config). Does not touch project-level
# opencode.json files. Restart opencode after install.
#
# ── What this does under the hood ────────────────────────────────────────────
# Equivalent manual setup (writes ~/.opencode/opencode.json + env var):
#
#   export SUBCONSCIOUS_API_KEY=sk-gw-...
#   cat > ~/.opencode/opencode.json <<'EOF'
#   {
#     "$schema": "https://opencode.ai/config.json",
#     "provider": {
#       "subconscious": {
#         "npm": "@ai-sdk/openai-compatible",
#         "name": "Subconscious Gateway",
#         "options": {
#           "baseURL": "https://your-gateway.example/v1",
#           "apiKey": "{env:SUBCONSCIOUS_API_KEY}",
#           "headers": { "x-subconscious-client": "opencode" }
#         },
#         "models": { "gw-glm-5.2": { "name": "gw-glm-5.2", "tools": true } }
#       }
#     },
#     "model": "subconscious/gw-glm-5.2"
#   }
#   EOF
#   opencode
#
# The x-subconscious-client header tells the gateway to classify traffic as
# OpenCode. OpenCode also sends native x-session-affinity / x-session-id
# headers for conversation correlation.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

COMMAND=""
GATEWAY_URL=""
API_KEY=""
MODEL="${OPENCODE_MODEL:-gw-glm-5.2}"

usage() {
  cat <<'EOF'
Usage:
  install.sh install --gateway-url URL --api-key KEY [--model MODEL]
  install.sh uninstall
  install.sh status

Writes an opencode.json that points opencode at your Subconscious gateway with
x-subconscious-client: opencode and x-session-affinity/x-session-id session
headers so the gateway can group requests into Conversations.

Requires: jq. Restart opencode after install.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    install|uninstall|status)
      COMMAND="$1"
      shift
      ;;
    --gateway-url)
      GATEWAY_URL="${2:-}"
      shift 2
      ;;
    --api-key)
      API_KEY="${2:-}"
      shift 2
      ;;
    --model)
      MODEL="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$COMMAND" ]]; then
  usage >&2
  exit 1
fi

OPENCODE_DIR="${HOME}/.opencode"
OPENCODE_CONFIG="${OPENCODE_DIR}/opencode.json"
MARKER='x-subconscious-client'

require_cmds() {
  local missing=0
  for c in jq; do
    if ! command -v "$c" >/dev/null 2>&1; then
      echo "missing required command: $c" >&2
      missing=1
    fi
  done
  if [[ "$missing" -ne 0 ]]; then
    exit 1
  fi
}

write_config() {
  mkdir -p "$OPENCODE_DIR"
  local base_url="${GATEWAY_URL%/}/v1"
  local config
  config=$(cat <<EOF
{
  "\$schema": "https://opencode.ai/config.json",
  "provider": {
    "subconscious": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "Subconscious Gateway",
      "options": {
        "baseURL": "${base_url}",
        "apiKey": "{env:SUBCONSCIOUS_API_KEY}",
        "headers": {
          "x-subconscious-client": "opencode"
        }
      },
      "models": {
        "${MODEL}": {
          "name": "${MODEL}",
          "tools": true
        }
      }
    }
  },
  "model": "subconscious/${MODEL}"
}
EOF
)
  echo "$config" >"$OPENCODE_CONFIG"
  # Also export the API key into the shell env file for interactive sessions.
  local env_file="${OPENCODE_DIR}/subconscious.env"
  umask 077
  cat >"$env_file" <<EOF
# Generated by ol-runbook/coding-agents/opencode/install.sh — do not commit secrets.
export SUBCONSCIOUS_API_KEY='${API_KEY}'
EOF
  chmod 600 "$env_file"
}

uninstall_config() {
  if [[ -f "$OPENCODE_CONFIG" ]] && grep -q "$MARKER" "$OPENCODE_CONFIG" 2>/dev/null; then
    rm -f "$OPENCODE_CONFIG"
  fi
  rm -f "${OPENCODE_DIR}/subconscious.env"
}

status() {
  echo "scope: user"
  echo "opencode dir: $OPENCODE_DIR"
  echo "config: $OPENCODE_CONFIG"
  if [[ -f "$OPENCODE_CONFIG" ]] && grep -q "$MARKER" "$OPENCODE_CONFIG" 2>/dev/null; then
    echo "status: installed"
    echo "model: $(jq -r '.model // "unset"' "$OPENCODE_CONFIG" 2>/dev/null || echo 'unknown')"
  else
    echo "status: not installed"
  fi
  if [[ -f "${OPENCODE_DIR}/subconscious.env" ]]; then
    echo "env: ${OPENCODE_DIR}/subconscious.env (present)"
  else
    echo "env: missing"
  fi
}

case "$COMMAND" in
  install)
    require_cmds
    if [[ -z "$GATEWAY_URL" || -z "$API_KEY" ]]; then
      echo "--gateway-url and --api-key are required for install" >&2
      exit 1
    fi
    write_config
    echo "Installed Subconscious OpenCode config at $OPENCODE_CONFIG"
    echo "Source the env file before launching opencode:"
    echo "  source ${OPENCODE_DIR}/subconscious.env"
    echo "Or export SUBCONSCIOUS_API_KEY in your shell profile."
    echo "Restart any running opencode sessions."
    ;;
  uninstall)
    uninstall_config
    echo "Removed Subconscious OpenCode config from $OPENCODE_DIR"
    ;;
  status)
    status
    ;;
esac
