targetScope = 'subscription'

@description('Azure region for the bootstrap foundation.')
param location string = 'eastus2'

@description('Resource group that will contain the bootstrap VM, VNet, state account, and platform resources.')
param resourceGroupName string

@description('Short deployment slug, used only for tags and deterministic names.')
param namePrefix string

@description('Bootstrap-owned VNet name.')
param virtualNetworkName string

@description('Dedicated, non-overlapping RFC1918 /16 for the whole gateway platform.')
param vnetCidr string

@description('Bootstrap subnet carved from the VNet.')
param bootstrapSubnetCidr string

@description('Terraform state storage account name.')
param stateStorageAccountName string

@description('Terraform state container name.')
param stateContainerName string = 'tfstate'

@description('User-assigned managed identity used by the bootstrap VM and infra runner.')
param identityName string

@description('Private bootstrap VM name.')
param vmName string

@description('Linux admin username for the VM. No inbound SSH is opened.')
param adminUsername string = 'azureuser'

@description('Ephemeral SSH public key generated by setup. The VM has no public IP or inbound SSH.')
param sshPublicKey string

@description('Existing Azure DNS zone name, for tagging and DNS-scope role assignment.')
param dnsZoneName string

@description('Resource group containing the existing Azure DNS zone.')
param dnsZoneResourceGroupName string

var tags = {
  project: 'api-gateway'
  deploy: namePrefix
  'managed-by': 'ol-runbook'
  template: 'api-gateway-azure-bootstrap'
}

resource rg 'Microsoft.Resources/resourceGroups@2025-04-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

module foundation 'resources.bicep' = {
  name: '${namePrefix}-bootstrap'
  scope: rg
  params: {
    location: location
    namePrefix: namePrefix
    virtualNetworkName: virtualNetworkName
    vnetCidr: vnetCidr
    bootstrapSubnetCidr: bootstrapSubnetCidr
    stateStorageAccountName: stateStorageAccountName
    stateContainerName: stateContainerName
    identityName: identityName
    vmName: vmName
    adminUsername: adminUsername
    sshPublicKey: sshPublicKey
    tags: tags
  }
}

resource dnsRg 'Microsoft.Resources/resourceGroups@2025-04-01' existing = {
  name: dnsZoneResourceGroupName
}

resource dnsZone 'Microsoft.Network/dnsZones@2023-07-01-preview' existing = {
  name: dnsZoneName
  scope: dnsRg
}

module dnsRoles 'dns-role-assignments.bicep' = {
  name: '${namePrefix}-dns-roles'
  scope: dnsRg
  params: {
    dnsZoneName: dnsZone.name
    runnerIdentityName: identityName
    runnerPrincipalId: foundation.outputs.identityPrincipalId
  }
}

output resourceGroupName string = rg.name
output virtualNetworkName string = foundation.outputs.virtualNetworkName
output vmName string = foundation.outputs.vmName
output identityClientId string = foundation.outputs.identityClientId
output identityPrincipalId string = foundation.outputs.identityPrincipalId
output stateStorageAccountName string = foundation.outputs.stateStorageAccountName
output stateContainerName string = foundation.outputs.stateContainerName
