#!/usr/bin/env bash
# ── Subconscious API Gateway — Cursor hooks setup ─────────────────────────────
# Install Cursor hooks that announce each agent handoff to your gateway so
# /v1/chat/completions requests are grouped into Conversations.
#
# Quick start:
#   ./install.sh install --gateway-url https://your-gateway.example --api-key sk-gw-...
#   ./install.sh status                 # show current hook config
#   ./install.sh uninstall              # remove hooks
#
# Cursor model/URL are set in Cursor settings (OpenAI API Key Override), not
# here. This script only installs the conversation-correlation hooks.
# Restart Cursor after install so it reloads ~/.cursor/hooks.json.
#
# ── What this does under the hood ────────────────────────────────────────────
# Equivalent manual setup (three pieces):
#
#   1. Cursor settings → enable "OpenAI API Key Override":
#        Base URL: https://your-gateway.example
#        API Key:  sk-gw-...
#
#   2. Write ~/.cursor/hooks.json pointing at the hook script:
#        {
#          "version": 1,
#          "hooks": {
#            "beforeSubmitPrompt": [{ "command": "~/.cursor/hooks/subconscious-hook.sh", "timeout": 2 }],
#            "afterAgentResponse":  [{ "command": "~/.cursor/hooks/subconscious-hook.sh", "timeout": 2 }],
#            "stop":                [{ "command": "~/.cursor/hooks/subconscious-hook.sh", "timeout": 2 }],
#            "subagentStart":       [{ "command": "~/.cursor/hooks/subconscious-hook.sh", "timeout": 2 }],
#            "subagentStop":        [{ "command": "~/.cursor/hooks/subconscious-hook.sh", "timeout": 2 }]
#          }
#        }
#
#   3. Write ~/.cursor/subconscious-hooks.env (mode 600):
#        export SUBCONSCIOUS_GATEWAY_URL=https://your-gateway.example
#        export SUBCONSCIOUS_API_KEY=sk-gw-...
#
# The hook script (hook.sh) POSTs turn_open/turn_heartbeat/turn_close to
# /v1/agent-hooks with a SHA-256 prompt fingerprint. The gateway soft-binds
# later LLM requests that share that fingerprint to group them into a
# Conversation. Unlike Claude Code / Pi / OpenCode, Cursor has no native
# session headers, so hooks are required for correlation.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SRC="${SCRIPT_DIR}/hook.sh"
HOOKS_TEMPLATE="${SCRIPT_DIR}/hooks.json"

# Load shared env from coding-agents/.env (gitignored) or env.example.
SHARED_ENV="${SCRIPT_DIR}/../.env"
[[ -f "$SHARED_ENV" ]] || SHARED_ENV="${SCRIPT_DIR}/../env.example"
if [[ -f "$SHARED_ENV" ]]; then set -a; source "$SHARED_ENV"; set +a; fi

GATEWAY_URL="${GATEWAY_URL:-}"
API_KEY="${API_KEY:-}"
COMMAND=""

usage() {
  cat <<'EOF'
Usage:
  install.sh install --gateway-url URL --api-key KEY
  install.sh uninstall
  install.sh status

Installs Cursor hooks (user-wide under ~/.cursor) that POST
turn_open/turn_heartbeat/turn_close to POST /v1/agent-hooks so the gateway
can group Conversations for Cursor traffic.

Requires: jq, curl, openssl (or shasum). Restart Cursor after install.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    install|uninstall|status)
      COMMAND="$1"
      shift
      ;;
    --gateway-url)
      GATEWAY_URL="${2:-}"
      shift 2
      ;;
    --api-key)
      API_KEY="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$COMMAND" ]]; then
  usage >&2
  exit 1
fi

CURSOR_DIR="${HOME}/.cursor"
HOOKS_JSON="${CURSOR_DIR}/hooks.json"
HOOK_DST="${CURSOR_DIR}/hooks/subconscious-hook.sh"
ENV_FILE="${CURSOR_DIR}/subconscious-hooks.env"
MARKER="subconscious-hook.sh"

require_cmds() {
  local missing=0
  for c in jq curl; do
    if ! command -v "$c" >/dev/null 2>&1; then
      echo "missing required command: $c" >&2
      missing=1
    fi
  done
  if ! command -v openssl >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
    echo "missing required command: openssl or shasum" >&2
    missing=1
  fi
  if [[ "$missing" -ne 0 ]]; then
    exit 1
  fi
}

write_env() {
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by ol-runbook/coding-agents/cursor/install.sh — do not commit secrets.
export SUBCONSCIOUS_GATEWAY_URL='${GATEWAY_URL}'
export SUBCONSCIOUS_API_KEY='${API_KEY}'
EOF
  chmod 600 "$ENV_FILE"
}

install_hook_script() {
  mkdir -p "$(dirname "$HOOK_DST")"
  cp "$HOOK_SRC" "$HOOK_DST"
  chmod +x "$HOOK_DST"
}

merge_hooks_json() {
  local tmp
  tmp="$(mktemp)"
  if [[ ! -f "$HOOKS_JSON" ]]; then
    sed "s|HOOK_SH_PATH|${HOOK_DST}|g" "$HOOKS_TEMPLATE" >"$HOOKS_JSON"
    return
  fi
  # Strip any prior subconscious entries, then append ours.
  jq --arg cmd "$HOOK_DST" '
    .version = (.version // 1) |
    .hooks = (.hooks // {}) |
    .hooks |= with_entries(
      .value = ((.value // []) | map(select((.command // "") | tostring | contains("subconscious-hook.sh") | not)))
    ) |
    .hooks.beforeSubmitPrompt = ((.hooks.beforeSubmitPrompt // []) + [{"command": $cmd, "timeout": 2}]) |
    .hooks.afterAgentResponse = ((.hooks.afterAgentResponse // []) + [{"command": $cmd, "timeout": 2}]) |
    .hooks.stop = ((.hooks.stop // []) + [{"command": $cmd, "timeout": 2}]) |
    .hooks.subagentStart = ((.hooks.subagentStart // []) + [{"command": $cmd, "timeout": 2}]) |
    .hooks.subagentStop = ((.hooks.subagentStop // []) + [{"command": $cmd, "timeout": 2}])
  ' "$HOOKS_JSON" >"$tmp"
  mv "$tmp" "$HOOKS_JSON"
}

uninstall_hooks() {
  if [[ -f "$HOOKS_JSON" ]]; then
    local tmp
    tmp="$(mktemp)"
    jq '
      .hooks //= {} |
      .hooks |= with_entries(
        .value = ((.value // []) | map(select((.command // "") | tostring | contains("subconscious-hook.sh") | not)))
      )
    ' "$HOOKS_JSON" >"$tmp"
    mv "$tmp" "$HOOKS_JSON"
  fi
  rm -f "$HOOK_DST" "$ENV_FILE"
}

status() {
  echo "scope: user"
  echo "cursor dir: $CURSOR_DIR"
  echo "hooks.json: $HOOKS_JSON"
  if [[ -f "$HOOKS_JSON" ]] && jq -e --arg m "$MARKER" '
      [.hooks[]?[]? | select((.command // "") | tostring | contains($m))] | length > 0
    ' "$HOOKS_JSON" >/dev/null 2>&1; then
    echo "hooks: installed"
  else
    echo "hooks: not installed"
  fi
  if [[ -f "$ENV_FILE" ]]; then
    echo "env: $ENV_FILE (present)"
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    echo "gateway: ${SUBCONSCIOUS_GATEWAY_URL:-unset}"
    if [[ -n "${SUBCONSCIOUS_API_KEY:-}" ]]; then
      echo "api key: set (${#SUBCONSCIOUS_API_KEY} chars)"
    else
      echo "api key: unset"
    fi
  else
    echo "env: missing"
  fi
  if [[ -x "$HOOK_DST" ]]; then
    echo "hook script: $HOOK_DST (executable)"
  else
    echo "hook script: missing"
  fi
}

case "$COMMAND" in
  install)
    require_cmds
    if [[ -z "$GATEWAY_URL" || -z "$API_KEY" ]]; then
      echo "--gateway-url and --api-key are required for install" >&2
      exit 1
    fi
    mkdir -p "$CURSOR_DIR"
    install_hook_script
    write_env
    merge_hooks_json
    echo "Installed Subconscious Cursor hooks into $CURSOR_DIR"
    echo "Restart Cursor to reload hooks.json."
    ;;
  uninstall)
    uninstall_hooks
    echo "Removed Subconscious Cursor hooks from $CURSOR_DIR"
    ;;
  status)
    status
    ;;
esac
